export const AvailableActions = {
  debug: {
    action: 'debug',
    description: 'Debug',
    args: {},
  },
  set_variable: {
    action: 'set_variable',
    description: 'Set Variable',
    args: {
      name: {
        name: 'name',
        type: 'string',
        description: 'Variable Name',
      },
      value: {
        name: 'value',
        type: 'string',
        description: 'Variable Value',
      },
    },
  },
  increment_variable: {
    action: 'increment_variable',
    description: 'Increment Variable',
    args: {
      name: {
        name: 'name',
        type: 'string',
        description: 'Variable Name',
      },
      amount: {
        name: 'amount',
        type: 'string',
        description: 'Increment Amount',
      },
    },
  },
  delete_variable: {
    action: 'delete_variable',
    description: 'Delete Variable',
    args: {
      name: {
        name: 'name',
        type: 'string',
        description: 'Variable Name',
      },
    },
  },
  sleep: {
    action: 'sleep',
    description: 'Sleep',
    args: {
      duration_ms: {
        name: 'duration_ms',
        type: 'string',
        description: 'Duration (in milliseconds)',
      },
    },
  },
  end_program: {
    action: 'end_program',
    description: 'End Program',
    args: {},
  },
  go_to_step: {
    action: 'go_to_step',
    description: 'Go To Step',
    args: {
      step: {
        name: 'step',
        type: 'string',
        description: 'Step',
      },
    },
  },
  go_to_step_relative: {
    action: 'go_to_step_relative',
    description: 'Go To Step Relative',
    args: {
      step: {
        name: 'step',
        type: 'string',
        description: 'Step',
      },
    },
  },
  if_else: {
    action: 'if_else',
    description: 'If Else',
    args: {
      operation: {
        name: 'operation',
        type: 'string',
        description: 'Operation',
      },
      a: {
        name: 'a',
        type: 'string',
        description: 'A',
      },
      b: {
        name: 'b',
        type: 'string',
        description: 'B',
      },
      step_true: {
        name: 'step_true',
        type: 'string',
        description: 'Step (True)',
      },
      step_false: {
        name: 'step_false',
        type: 'string',
        description: 'Step (False)',
      },
    },
  },
  if_else_relative: {
    action: 'if_else_relative',
    description: 'If Else Relative',
    args: {
      operation: {
        name: 'operation',
        type: 'string',
        description: 'Operation',
      },
      a: {
        name: 'a',
        type: 'string',
        description: 'A',
      },
      b: {
        name: 'b',
        type: 'string',
        description: 'B',
      },
      step_true: {
        name: 'step_true',
        type: 'string',
        description: 'Step (True)',
      },
      step_false: {
        name: 'step_false',
        type: 'string',
        description: 'Step (False)',
      },
    },
  },
  spawn: {
    action: 'spawn',
    description: 'Spawn',
    args: {
      command: {
        name: 'command',
        type: 'string',
        description: 'Command',
      },
      args: {
        name: 'args',
        type: 'string',
        description: 'Args',
      },
    },
  },
  print_console: {
    action: 'print_console',
    description: 'Print Console',
    args: {
      content: {
        name: 'content',
        type: 'string',
        description: 'Content',
      },
    },
  },
  show_dialog: {
    action: 'show_dialog',
    description: 'Show Dialog',
    args: {
      title: {
        name: 'title',
        type: 'string',
        description: 'Title',
      },
      body: {
        name: 'body',
        type: 'string',
        description: 'Body',
      },
    },
  },
  read_clipboard: {
    action: 'read_clipboard',
    description: 'Read Clipboard',
    args: {},
  },
  write_clipboard: {
    action: 'write_clipboard',
    description: 'Write Clipboard',
    args: {
      content: {
        name: 'content',
        type: 'string',
        description: 'Content',
      },
    },
  },
  ask_chatgpt: {
    action: 'ask_chatgpt',
    description: 'Ask Chatgpt',
    args: {
      pre_prompt: {
        name: 'pre_prompt',
        type: 'string',
        description: 'Pre Prompt',
      },
      prompt: {
        name: 'prompt',
        type: 'string',
        description: 'Prompt',
      },
    },
  },
} as const

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Action =
  | { action: 'debug' }
  | { action: 'set_variable'; name: string; value: string }
  | { action: 'increment_variable'; name: string; amount: string }
  | { action: 'delete_variable'; name: string }
  | { action: 'sleep'; duration_ms: string }
  | { action: 'end_program' }
  | { action: 'go_to_step'; step: string }
  | { action: 'go_to_step_relative'; step: string }
  | {
      action: 'if_else'
      operation: string
      a: string
      b: string
      step_true: string
      step_false: string
    }
  | {
      action: 'if_else_relative'
      operation: string
      a: string
      b: string
      step_true: string
      step_false: string
    }
  | { action: 'spawn'; command: string; args: Array<string> }
  | { action: 'print_console'; content: string }
  | { action: 'show_dialog'; title: string; body: string }
  | { action: 'read_clipboard' }
  | { action: 'write_clipboard'; content: string }
  | { action: 'ask_chatgpt'; pre_prompt: string; prompt: string }
