// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NumberComparison } from "./NumberComparison";
import type { StringComparison } from "./StringComparison";

export type Comparison = NumberComparison | StringComparison;
