export enum KeybdKey {
  'BackspaceKey' = 'BackspaceKey',
  'TabKey' = 'TabKey',
  'EnterKey' = 'EnterKey',
  'EscapeKey' = 'EscapeKey',
  'SpaceKey' = 'SpaceKey',
  'PageUpKey' = 'PageUpKey',
  'PageDownKey' = 'PageDownKey',
  'EndKey' = 'EndKey',
  'HomeKey' = 'HomeKey',
  'LeftKey' = 'LeftKey',
  'UpKey' = 'UpKey',
  'RightKey' = 'RightKey',
  'DownKey' = 'DownKey',
  'InsertKey' = 'InsertKey',
  'DeleteKey' = 'DeleteKey',
  'Numrow0Key' = 'Numrow0Key',
  'Numrow1Key' = 'Numrow1Key',
  'Numrow2Key' = 'Numrow2Key',
  'Numrow3Key' = 'Numrow3Key',
  'Numrow4Key' = 'Numrow4Key',
  'Numrow5Key' = 'Numrow5Key',
  'Numrow6Key' = 'Numrow6Key',
  'Numrow7Key' = 'Numrow7Key',
  'Numrow8Key' = 'Numrow8Key',
  'Numrow9Key' = 'Numrow9Key',
  'AKey' = 'AKey',
  'BKey' = 'BKey',
  'CKey' = 'CKey',
  'DKey' = 'DKey',
  'EKey' = 'EKey',
  'FKey' = 'FKey',
  'GKey' = 'GKey',
  'HKey' = 'HKey',
  'IKey' = 'IKey',
  'JKey' = 'JKey',
  'KKey' = 'KKey',
  'LKey' = 'LKey',
  'MKey' = 'MKey',
  'NKey' = 'NKey',
  'OKey' = 'OKey',
  'PKey' = 'PKey',
  'QKey' = 'QKey',
  'RKey' = 'RKey',
  'SKey' = 'SKey',
  'TKey' = 'TKey',
  'UKey' = 'UKey',
  'VKey' = 'VKey',
  'WKey' = 'WKey',
  'XKey' = 'XKey',
  'YKey' = 'YKey',
  'ZKey' = 'ZKey',
  'LSuper' = 'LSuper',
  'RSuper' = 'RSuper',
  'Numpad0Key' = 'Numpad0Key',
  'Numpad1Key' = 'Numpad1Key',
  'Numpad2Key' = 'Numpad2Key',
  'Numpad3Key' = 'Numpad3Key',
  'Numpad4Key' = 'Numpad4Key',
  'Numpad5Key' = 'Numpad5Key',
  'Numpad6Key' = 'Numpad6Key',
  'Numpad7Key' = 'Numpad7Key',
  'Numpad8Key' = 'Numpad8Key',
  'Numpad9Key' = 'Numpad9Key',
  'F1Key' = 'F1Key',
  'F2Key' = 'F2Key',
  'F3Key' = 'F3Key',
  'F4Key' = 'F4Key',
  'F5Key' = 'F5Key',
  'F6Key' = 'F6Key',
  'F7Key' = 'F7Key',
  'F8Key' = 'F8Key',
  'F9Key' = 'F9Key',
  'F10Key' = 'F10Key',
  'F11Key' = 'F11Key',
  'F12Key' = 'F12Key',
  'F13Key' = 'F13Key',
  'F14Key' = 'F14Key',
  'F15Key' = 'F15Key',
  'F16Key' = 'F16Key',
  'F17Key' = 'F17Key',
  'F18Key' = 'F18Key',
  'F19Key' = 'F19Key',
  'F20Key' = 'F20Key',
  'F21Key' = 'F21Key',
  'F22Key' = 'F22Key',
  'F23Key' = 'F23Key',
  'F24Key' = 'F24Key',
  'NumLockKey' = 'NumLockKey',
  'ScrollLockKey' = 'ScrollLockKey',
  'CapsLockKey' = 'CapsLockKey',
  'LShiftKey' = 'LShiftKey',
  'RShiftKey' = 'RShiftKey',
  'LControlKey' = 'LControlKey',
  'RControlKey' = 'RControlKey',
  'LAltKey' = 'LAltKey',
  'RAltKey' = 'RAltKey',
  'BrowserBackKey' = 'BrowserBackKey',
  'BrowserForwardKey' = 'BrowserForwardKey',
  'BrowserRefreshKey' = 'BrowserRefreshKey',
  'VolumeMuteKey' = 'VolumeMuteKey',
  'VolumeDownKey' = 'VolumeDownKey',
  'VolumeUpKey' = 'VolumeUpKey',
  'MediaNextTrackKey' = 'MediaNextTrackKey',
  'MediaPrevTrackKey' = 'MediaPrevTrackKey',
  'MediaStopKey' = 'MediaStopKey',
  'MediaPlayPauseKey' = 'MediaPlayPauseKey',
  'BackquoteKey' = 'BackquoteKey',
  'SlashKey' = 'SlashKey',
  'BackslashKey' = 'BackslashKey',
  'CommaKey' = 'CommaKey',
  'PeriodKey' = 'PeriodKey',
  'MinusKey' = 'MinusKey',
  'QuoteKey' = 'QuoteKey',
  'SemicolonKey' = 'SemicolonKey',
  'LBracketKey' = 'LBracketKey',
  'RBracketKey' = 'RBracketKey',
  'EqualKey' = 'EqualKey',
}

//
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type KeybdKeyDef =
  | 'BackspaceKey'
  | 'TabKey'
  | 'EnterKey'
  | 'EscapeKey'
  | 'SpaceKey'
  | 'PageUpKey'
  | 'PageDownKey'
  | 'EndKey'
  | 'HomeKey'
  | 'LeftKey'
  | 'UpKey'
  | 'RightKey'
  | 'DownKey'
  | 'InsertKey'
  | 'DeleteKey'
  | 'Numrow0Key'
  | 'Numrow1Key'
  | 'Numrow2Key'
  | 'Numrow3Key'
  | 'Numrow4Key'
  | 'Numrow5Key'
  | 'Numrow6Key'
  | 'Numrow7Key'
  | 'Numrow8Key'
  | 'Numrow9Key'
  | 'AKey'
  | 'BKey'
  | 'CKey'
  | 'DKey'
  | 'EKey'
  | 'FKey'
  | 'GKey'
  | 'HKey'
  | 'IKey'
  | 'JKey'
  | 'KKey'
  | 'LKey'
  | 'MKey'
  | 'NKey'
  | 'OKey'
  | 'PKey'
  | 'QKey'
  | 'RKey'
  | 'SKey'
  | 'TKey'
  | 'UKey'
  | 'VKey'
  | 'WKey'
  | 'XKey'
  | 'YKey'
  | 'ZKey'
  | 'LSuper'
  | 'RSuper'
  | 'Numpad0Key'
  | 'Numpad1Key'
  | 'Numpad2Key'
  | 'Numpad3Key'
  | 'Numpad4Key'
  | 'Numpad5Key'
  | 'Numpad6Key'
  | 'Numpad7Key'
  | 'Numpad8Key'
  | 'Numpad9Key'
  | 'F1Key'
  | 'F2Key'
  | 'F3Key'
  | 'F4Key'
  | 'F5Key'
  | 'F6Key'
  | 'F7Key'
  | 'F8Key'
  | 'F9Key'
  | 'F10Key'
  | 'F11Key'
  | 'F12Key'
  | 'F13Key'
  | 'F14Key'
  | 'F15Key'
  | 'F16Key'
  | 'F17Key'
  | 'F18Key'
  | 'F19Key'
  | 'F20Key'
  | 'F21Key'
  | 'F22Key'
  | 'F23Key'
  | 'F24Key'
  | 'NumLockKey'
  | 'ScrollLockKey'
  | 'CapsLockKey'
  | 'LShiftKey'
  | 'RShiftKey'
  | 'LControlKey'
  | 'RControlKey'
  | 'LAltKey'
  | 'RAltKey'
  | 'BrowserBackKey'
  | 'BrowserForwardKey'
  | 'BrowserRefreshKey'
  | 'VolumeMuteKey'
  | 'VolumeDownKey'
  | 'VolumeUpKey'
  | 'MediaNextTrackKey'
  | 'MediaPrevTrackKey'
  | 'MediaStopKey'
  | 'MediaPlayPauseKey'
  | 'BackquoteKey'
  | 'SlashKey'
  | 'BackslashKey'
  | 'CommaKey'
  | 'PeriodKey'
  | 'MinusKey'
  | 'QuoteKey'
  | 'SemicolonKey'
  | 'LBracketKey'
  | 'RBracketKey'
  | 'EqualKey'
