// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NumberComparison =
  | { operation: "=="; a: number; b: number }
  | { operation: "!="; a: number; b: number }
  | { operation: "<"; a: number; b: number }
  | { operation: "<="; a: number; b: number }
  | { operation: ">"; a: number; b: number }
  | { operation: ">="; a: number; b: number };
