// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StringComparison =
  | { operation: "equals"; a: string; b: string }
  | { operation: "not_equals"; a: string; b: string }
  | { operation: "contains"; a: string; b: string }
  | { operation: "not_contains"; a: string; b: string }
  | { operation: "starts_with"; a: string; b: string }
  | { operation: "ends_with"; a: string; b: string }
  | { operation: "is_empty"; a: string }
  | { operation: "is_not_empty"; a: string };
